fields:
  domain:
    name: Domain
  progress:
    name: Progress
  status:
    name: Status
    options:
      FAIL: Backlog
      OK: Done
      WARN: In progress
  subtasks:
    name: Subtasks
project:
  enabled: true
  number: 4
  owner: AmirTlinov
  runtime_disabled_reason: Could not resolve to a Repository with the name 'octo/demo'.
  type: user
  workers: 0
